USE [master]
GO

IF DB_ID('BonSai_DB') IS NOT NULL
BEGIN
    --DROP DATABASE [BonSai_DB]
	ALTER DATABASE [BonSai_DB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [BonSai_DB];
END
GO
CREATE DATABASE [BonSai_DB]
GO

USE [BonSai_DB]
GO


CREATE TABLE [User] 
( 
    Id INT IDENTITY(1,1) NOT NULL,
    UserName NVARCHAR(50) NOT NULL,
    [Password] NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    DOB DATE NOT NULL,
    [Address] NVARCHAR(100) NOT NULL,
    Phone_Number NVARCHAR(50) NOT NULL,
    [RoleName] NVARCHAR(50) NOT NULL,
    [Gender] NVARCHAR(50) NOT NULL,
    [ImgURL] NVARCHAR(MAX) NOT NULL,
    Created_Date DATE NOT NULL,
    Modified_Date DATE NULL,
    [Rating_Count] INT NULL,
    [Status] BIT NOT NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO
CREATE TABLE [Category] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


CREATE TABLE [Product] 
(
    Id INT IDENTITY(1,1) NOT NULL,
	[User_Id] INT NOT NULL,
	[Category_Id] INT NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
	[Price] FLOAT NOT NULL,
	[Quantity] INT NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
	[Story] NVARCHAR(MAX) NULL,
	[Score] INT NULL,
    [Status] BIT NOT NULL, 
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
FOREIGN KEY ([Category_Id]) REFERENCES [Category] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Order] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [User_Id] INT NOT NULL,
    [Total_Price] FLOAT NOT NULL,
	[ShipPrice] FLOAT NOT NULL,
    [Date] DATE NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
    [Status] INT NOT NULL,
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO
CREATE TABLE [OrderActivity] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Order_Id] INT NOT NULL,
	[Update_Date] DATE NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
    [Status] INT NOT NULL,
FOREIGN KEY ([Order_Id]) REFERENCES [User] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Payment] 
(
    [Id] INT IDENTITY(1,1) NOT NULL,
	[User_Id] INT NOT NULL,
	[Order_Id] INT NOT NULL,
    [Date] NVARCHAR(MAX) NOT NULL,
    [Amount] FLOAT NOT NULL,
    [Method] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL, 
    [Status] BIT NOT NULL, 
FOREIGN KEY ([Order_Id]) REFERENCES [Order]([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [OrderDetails] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Order_Id] INT NOT NULL,
    [Product_Id] INT NOT NULL,
	[Quantity] INT NOT NULL,
    [Price] FLOAT NOT NULL,
	[Status_Rating] BIT NOT NULL,
	[Comment] NVARCHAR(MAX) NULL,
	[Score] INT NULL,
    [Status] BIT NOT NULL,
FOREIGN KEY ([Product_Id]) REFERENCES [Product]([Id]),
FOREIGN KEY ([Order_Id]) REFERENCES [Order] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO



