USE [master]
GO

IF DB_ID('FootballShop_DB') IS NOT NULL
BEGIN
    --DROP DATABASE [FootballShop_DB]
	ALTER DATABASE [FootballShop_DB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [FootballShop_DB];
END
GO
CREATE DATABASE [FootballShop_DB]
GO

USE [FootballShop_DB]
GO


CREATE TABLE [User] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    UserName NVARCHAR(50) NOT NULL,
    [Password] NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    DOB DATE NOT NULL,
    [Address] NVARCHAR(100) NOT NULL,
    Phone_Number NVARCHAR(50) NOT NULL,
    [RoleName] NVARCHAR(50) NOT NULL,
    [Gender] NVARCHAR(50) NOT NULL,
    [ImgURL] NVARCHAR(MAX) NOT NULL,
    Created_Date DATE NOT NULL,
    Modified_Date DATE NULL,
    [Rating_Count] INT NULL,
    [Status] BIT NOT NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


CREATE TABLE [Club] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
	[Country] NVARCHAR(100) NOT NULL,
	[EstablishedYear] DATETIME NOT NULL,
	[StadiumName] NVARCHAR(100) NOT NULL,
	[ClubLogo] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Player] (
    Id INT IDENTITY(1,1),
	[Club_Id] INT NUll,
    FullName NVARCHAR(50) NOT NULL,
	height FlOAT NULL,
    [weight] FlOAT NULL,
    Birthday DATE NULL,
    Nationality NVARCHAR(50) NULL,
FOREIGN KEY (Club_Id) REFERENCES [Club](id),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Session] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
	[StartDdate] DATETIME NOT NULL,
	[EndDdate] DATETIME NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [TypeShirt] 
(
    Id INT IDENTITY(1,1) NOT NULL,
	[Session_Id] INT NOT NULL,
	[Club_Id] INT NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
FOREIGN KEY ([Session_Id]) REFERENCES [Session] ([Id]),
FOREIGN KEY ([Club_Id]) REFERENCES [Club] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


CREATE TABLE [Shirt] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [TypeShirt_Id] INT NOT NULL,
	[Player_Id] INT NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
	[Number] INT NULL,
    [Price] FLOAT NOT NULL,
	[Date] DATETIME NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Url_IMG] NVARCHAR(MAX) NULL, 
    [Status] INT NOT NULL, 
FOREIGN KEY ([Player_Id]) REFERENCES [Player] ([Id]),
FOREIGN KEY ([TypeShirt_Id]) REFERENCES [TypeShirt]([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO
CREATE TABLE [Inventory] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Shirt_Id] INT NOT NULL,
    [Quantity] FLOAT NOT NULL,
	[Date] DATETIME NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] INT NOT NULL, 
FOREIGN KEY ([Shirt_Id]) REFERENCES [Shirt]([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


CREATE TABLE [Notification] 
(
    [Id] INT IDENTITY(1,1) PRIMARY KEY,
    [User_Id] INT NOT NULL,
    [Content] NVARCHAR(MAX) NOT NULL,
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
) ON [PRIMARY];
GO

CREATE TABLE [Order] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [User_Id] INT NOT NULL,
    [Total_Price] FLOAT NOT NULL,
	[ShipPrice] FLOAT NOT NULL,
	[Deposit] FLOAT NOT NULL,
    [Date] DATE NOT NULL,
	[RefundStatus] BIT NOT NULL,
    [Status] INT NOT NULL,
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Payment] 
(
    [Id] INT IDENTITY(1,1) NOT NULL,
	[User_Id] INT NOT NULL,
	[Order_Id] INT NOT NULL,
    [Date] NVARCHAR(MAX) NOT NULL,
    [Amount] FLOAT NOT NULL,
    [Method] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL, 
    [Status] BIT NOT NULL, 
FOREIGN KEY ([User_Id]) REFERENCES [User]([Id]),
FOREIGN KEY ([Order_Id]) REFERENCES [Order]([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [OrderDetails] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Order_Id] INT NOT NULL,
    [Shirt_Id] INT NOT NULL,
	[Quantity] INT NOT NULL,
    [Price] FLOAT NOT NULL,
	[Status_Rating] BIT NOT NULL,
	[Comment] NVARCHAR(MAX) NULL,
	[Score] INT NULL,
    [Status] BIT NOT NULL,
FOREIGN KEY ([Shirt_Id]) REFERENCES [Shirt] ([Id]),
FOREIGN KEY ([Order_Id]) REFERENCES [Order] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO











