USE [master]
GO

IF DB_ID('FootballShop_DB') IS NOT NULL
BEGIN
    --DROP DATABASE [FootballShop_DB]
	ALTER DATABASE [FootballShop_DB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [FootballShop_DB];
END
GO
CREATE DATABASE [FootballShop_DB]
GO

USE [FootballShop_DB]
GO


CREATE TABLE [User] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    UserName NVARCHAR(50) NOT NULL,
    [Password] NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    DOB DATE NOT NULL,
    [Address] NVARCHAR(100) NOT NULL,
    Phone_Number NVARCHAR(50) NOT NULL,
    [RoleName] NVARCHAR(50) NOT NULL,
    [Gender] NVARCHAR(50) NOT NULL,
    [ImgURL] NVARCHAR(MAX) NOT NULL,
    Created_Date DATE NOT NULL,
    Modified_Date DATE NULL,
    [Rating_Count] INT NULL,
    [Status] BIT NOT NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


CREATE TABLE [BannedAccount] 
(
    [Id] INT IDENTITY(1,1) NOT NULL,
    [User_Id] INT NOT NULL,
    [Description] NVARCHAR(Max) NOT NULL,
    [Date] DATETIME NOT NULL,
    [Modified_Date] DATETIME NULL,
    [Status] BIT NOT NULL,
FOREIGN KEY ([User_Id]) REFERENCES [User]([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


CREATE TABLE [Category] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Club] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
	[Country] NVARCHAR(100) NOT NULL,
	[EstablishedYear] DATETIME NOT NULL,
	[StadiumName] NVARCHAR(100) NOT NULL,
	[ClubLogo] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Session] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
	[StartDdate] DATETIME NOT NULL,
	[EndDdate] DATETIME NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Club_Session] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Club_Id] INT NOT NULL,
	[Session_Id] INT NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
FOREIGN KEY ([Club_Id]) REFERENCES [Club] ([Id]),
FOREIGN KEY ([Session_Id]) REFERENCES [Session] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [ShirtModel] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


CREATE TABLE [Product] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [User_Id] INT NOT NULL,
    [Category_Id] INT NOT NULL,
	[Club_Session_Id] INT NOT NULL,
	[ShirtModel_Id] INT NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
    [Price] FLOAT NOT NULL,
	[Date] DATETIME NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Url_IMG] NVARCHAR(MAX) NULL, 
    [Status] INT NOT NULL, 
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
FOREIGN KEY ([Club_Session_Id]) REFERENCES [Club_Session] ([Id]),
FOREIGN KEY ([ShirtModel_Id]) REFERENCES [ShirtModel] ([Id]),
FOREIGN KEY ([Category_Id]) REFERENCES [Category]([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO
CREATE TABLE [Inventory] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [User_Id] INT NOT NULL,
    [Product_Id] INT NOT NULL,
    [Quantity] FLOAT NOT NULL,
	[Date] DATETIME NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] INT NOT NULL, 
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
FOREIGN KEY ([Product_Id]) REFERENCES [Product]([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


CREATE TABLE [Notification] 
(
    [Id] INT IDENTITY(1,1) PRIMARY KEY,
    [User_Id] INT NOT NULL,
    [Content] NVARCHAR(MAX) NOT NULL,
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
) ON [PRIMARY];
GO

CREATE TABLE [Cart] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [User_Id] INT NOT NULL,
    [Total_Price] FLOAT NOT NULL,
    [Status] INT NOT NULL,
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [CartItem] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Cart_Id] INT NOT NULL,
    [Product_Id] INT NOT NULL,
	[Quantity] INT NOT NULL,
    [Status] INT NOT NULL,
FOREIGN KEY ([Cart_Id]) REFERENCES [Cart] ([Id]),
FOREIGN KEY ([Product_Id]) REFERENCES [Product] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO


CREATE TABLE [Order] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [User_Id] INT NOT NULL,
    [Total_Price] FLOAT NOT NULL,
	[ShipPrice] FLOAT NOT NULL,
	[Deposit] FLOAT NOT NULL,
    [Date] DATE NOT NULL,
    [Status] INT NOT NULL,
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Payment] 
(
    [Id] INT IDENTITY(1,1) NOT NULL,
	[User_Id] INT NOT NULL,
	[Order_Id] INT NOT NULL,
    [Date] NVARCHAR(MAX) NOT NULL,
    [Amount] FLOAT NOT NULL,
    [Method] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL, 
    [Status] BIT NOT NULL, 
FOREIGN KEY ([User_Id]) REFERENCES [User]([Id]),
FOREIGN KEY ([Order_Id]) REFERENCES [Order]([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [OrderDetails] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Order_Id] INT NOT NULL,
    [Product_Id] INT NOT NULL,
	[Quantity] INT NOT NULL,
    [Price] FLOAT NOT NULL,
	[Status_Rating] BIT NOT NULL,
    [Status] BIT NOT NULL,
FOREIGN KEY ([Product_Id]) REFERENCES [Product] ([Id]),
FOREIGN KEY ([Order_Id]) REFERENCES [Order] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [DeliveryProgress] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [Order_Id] INT NOT NULL,
	[Date] DATETIME NOT NULL,
    [Description] NVARCHAR(MAX) NOT NULL,
    [Status] INT NOT NULL,
FOREIGN KEY ([Order_Id]) REFERENCES [Order] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Rating] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [User_Id] INT NOT NULL,
	[Order_Id] INT NOT NULL,
	[Product_Id] INT NOT NULL,
    [Score] INT NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [DATE] DATETIME NOT NULL,
    [Status] BIT NOT NULL, 
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
FOREIGN KEY ([Order_Id]) REFERENCES [Order] ([Id]),
FOREIGN KEY ([Product_Id]) REFERENCES [Product] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [RefundMethod] 
(
    Id INT IDENTITY(1,1) NOT NULL,
	[Method] NVARCHAR(MAX) NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Status] BIT NOT NULL, 
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [Refund] 
(
    Id INT IDENTITY(1,1) NOT NULL,
    [User_Id] INT NOT NULL,
	[Order_Id] INT NOT NULL,
	[RefundMethod_Id] INT NOT NULL,
	[Product_Id] INT NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Date] DATETIME NOT NULL,
    [Status] INT NOT NULL, 
FOREIGN KEY ([User_Id]) REFERENCES [User] ([Id]),
FOREIGN KEY ([Order_Id]) REFERENCES [Order] ([Id]),
FOREIGN KEY ([RefundMethod_Id]) REFERENCES [RefundMethod] ([Id]),
FOREIGN KEY ([Product_Id]) REFERENCES [Product] ([Id]),
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO








